'use strict';

var htmlMsgKey = require('./htmlMsg-key');
var htmlMsg = {};

htmlMsg[htmlMsgKey.INBOX_FOLLOW.str] = '<b>{0}</b> ha comenzado a seguirte.';
htmlMsg[htmlMsgKey.INBOX_LIKE.str] = '<b>{0}</b> le ha gustado tu post: <b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_COMMENT.str] = '<b>{0}</b> ha dejado un comentario en tu post.';
htmlMsg[htmlMsgKey.INBOX_MENTIONPOST.str] = '<b>{0}</b> te ha mencionado en un post.';
htmlMsg[htmlMsgKey.INBOX_MENTIONCOMMENT.str] = '<b>{0}</b> te he mencionado en un comentario.';
htmlMsg[htmlMsgKey.INBOX_GROUPCREATED.str] = '<b>{0}</b> ha creado el grupo <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_INVITE.str] = '<b>{0}</b> te ha invitado al grupo <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_ACCEPTED.str] = '<b>{0}</b> ha aceptado tu invitacion a el grupo <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_KICKED.str] = '';
htmlMsg[htmlMsgKey.INBOX_GROUPDELETED.str] = '<b>{0}</b> ha borrado el grupo <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_POSTGROUP.str] = '<b>{0}</b> ha creado un post en <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_CONTEST_PERFORMANCE.str] = '<b>{0}</b> Actual Top 3: \n1st: <b>{1}</b>, <b>{2}</b> <b>{3}</b> \n2nd: <b>{4}</b>, <b>{5}</b> <b>{6}</b> \n3rd: <b>{7}</b>, {8} {9}';
htmlMsg[htmlMsgKey.INBOX_REQUESTTOJOIN.str] = '<b>{0}</b> ha solicitado unirse al grupo <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_APPROVETOJOIN.str] = '<b>{0}</b> ha aprobado tu solicitud para unirte al grupo <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_ECONCALENDAR.str] = '[{0}] <b>{1}</b> será publicado <b>{2}</b>';
htmlMsg[htmlMsgKey.INBOX_COMMENTLIKE.str] = '<b>{0}</b> le ha gustado tu comentario: <b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_TOP_PERFORMANCE.str] = '¡Buen trabajo! Actualmente estás en el top <b>{1}</b> de el <b>{0}</b>';
htmlMsg[htmlMsgKey.INBOX_CONTEST_FINAL_RANKING.str] = 'Finales Top3 <b>{0}</b>: \n1ro: <b>{1}</b>, <b>{2}</b> <b>{3}</b>, gana <b>{4}</b>{5} \n2do: <b>{6}</b>, {7} {8}, gana {9}{10} \n3to: <b>{11}</b>, {12} {13}, gana {14}{15}';
htmlMsg[htmlMsgKey.INBOX_CONTEST_CANCELLED.str] = 'Lo siento, <b>{0}</b> ha sido cancelado.';
htmlMsg[htmlMsgKey.INBOX_CONTEST_ACTIVATED.str] = '<b>{0}</b> ha sido activado! Comenzará en <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_CONTEST_NEED_PEOPLE.str] = 'Ya casi estás allì! Solo <b>{0}</b> personas más para activar <b>{1}</b>.';
htmlMsg[htmlMsgKey.INBOX_CONTEST_START_SOON.str] = '<b>{0}</b> comienza mañana! Buena Suerte!';
htmlMsg[htmlMsgKey.INBOX_CONTEST_END_SOON.str] = '<b>{0}</b> finaliza en <b>{1}</b> día(s). Buena Suerte!';
htmlMsg[htmlMsgKey.INBOX_CONTEST_INVITATION.str] = '<b>{0}</b> te ha invitado a unirte al grupo <b>{1}</b>.';
htmlMsg[htmlMsgKey.REFERRAL_INVALID_CODE.str] = 'Your code is invalid, please try again.';
htmlMsg[htmlMsgKey.REFERRAL_MUTUAL_INVITE.str] = 'You already invited <b>{0}</b> to join, try another one!';
htmlMsg[htmlMsgKey.REFERRAL_INVITE_SELF.str] = 'You cannot invite yourself';
htmlMsg[htmlMsgKey.REFERRAL_CONFIRMED.str] = 'Tu código de referencia ha sido confirmado por <b>{0}</b>, has recibido una moneda!';
htmlMsg[htmlMsgKey.FUEL_EXCHANGE.str] = 'Good job! Your FDT Fuel score is above <b>{0}</b>! You can now exchange <b>{1}</b> fuel points for {1} coin.';
htmlMsg[htmlMsgKey.FUEL_FULL.str] = 'Wow! Your FDT Fuel is full! Exchange for coins now!';
htmlMsg[htmlMsgKey.FUEL_LOW.str] = 'Your FDT Fuel is almost consumed. Make trades or post on “Timelines” to gain more Fuel now!';
htmlMsg[htmlMsgKey.SCHOOL_PASS.str] = 'Your student ID is verified!';
htmlMsg[htmlMsgKey.SCHOOL_REJECTED.str] = 'Your student ID is invalid or inconsistent with the format, please re-upload or contact customer service staff. (Please verify your student ID ASAP in order to appear on the ranking list when you participate in a campus contest.)';
htmlMsg[htmlMsgKey.SCHOOL_REMIND.str] = 'Your student ID will be expiring soon, please upload your new student ID as soon as possible.';
htmlMsg[htmlMsgKey.SCHOOL_EXPIRED.str] = 'Your student ID has expired, please upload a new student ID. (Please verify your student ID again ASAP in order to appear on the ranking list when you participate in a campus contest.)';

module.exports = htmlMsg;
