'use strict';

var htmlMsgKey = require('./htmlMsg-key');
var htmlMsg = {};

htmlMsg[htmlMsgKey.INBOX_FOLLOW.str] = '<b>{0}</b>があなたをフォローしました';
htmlMsg[htmlMsgKey.INBOX_LIKE.str] = '<b>{0}</b>があなたの投稿にいいねといっています';
htmlMsg[htmlMsgKey.INBOX_COMMENT.str] = '<b>{0}</b>があなたの投稿にコメントしました';
htmlMsg[htmlMsgKey.INBOX_MENTIONPOST.str] = '<b>{0}</b>があなたについて投稿しました';
htmlMsg[htmlMsgKey.INBOX_MENTIONCOMMENT.str] = '<b>{0}</b>があなたについてコメントしました: <b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_GROUPCREATED.str] = '<b>{0}</b>がグループをつくりました<b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_INVITE.str] = '<b>{0}</b>があなたをグループに招待しています<b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_ACCEPTED.str] = '<b>{0}</b>があなたの招待を承認しました<b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_KICKED.str] = '';
htmlMsg[htmlMsgKey.INBOX_GROUPDELETED.str] = '<b>{0}</b>がグループを削除しました<b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_POSTGROUP.str] = '<b>{0}</b>が{1}に投稿しました';
htmlMsg[htmlMsgKey.INBOX_CONTEST_PERFORMANCE.str] = '<b>{0}</b> 暫定トップ3: \n1st: <b>{1}</b>, <b>{2}</b> <b>{3}</b> \n2nd: <b>{4}</b>, <b>{5}</b> {6} \n3rd: <b>{7}</b>, {8} {9}';
htmlMsg[htmlMsgKey.INBOX_REQUESTTOJOIN.str] = '<b>{0}</b>があなたのグループへの参加を求めています <b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_APPROVETOJOIN.str] = '<b>{0}</b>がグループ参加リクエストを承認しました<b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_ECONCALENDAR.str] = '[{0}] <b>{1}</b>は{2}に公開されます';
htmlMsg[htmlMsgKey.INBOX_COMMENTLIKE.str] = '<b>{0}</b>があなたのコメントにいいねといっています:<b>{1}</b>';
htmlMsg[htmlMsgKey.INBOX_TOP_PERFORMANCE.str] = 'すばらしい！あなたは今<b>{0}</b>の暫定トップ{1}です';
htmlMsg[htmlMsgKey.INBOX_CONTEST_FINAL_RANKING.str] = '<b>{0}</b> の最終トップ3: \n1位: <b>{1}</b>, <b>{2}</b> <b>{3}</b>, win <b>{4}</b>{5} \n2位: <b>{6}</b>, {7} {8}, win {9}{10} \n3位: <b>{11}</b>, {12} {13}, win {14}{15}';
htmlMsg[htmlMsgKey.INBOX_CONTEST_CANCELLED.str] = '<b>{0}</b>はキャンセルされました';
htmlMsg[htmlMsgKey.INBOX_CONTEST_ACTIVATED.str] = '<b>{0}</b>が{1}に開始します！';
htmlMsg[htmlMsgKey.INBOX_CONTEST_NEED_PEOPLE.str] = '<b>{0}</b>を開始させるにはあと<b>{1}</b>人の参加が必要です';
htmlMsg[htmlMsgKey.INBOX_CONTEST_START_SOON.str] = '<b>{0}</b>は明日開始されます！頑張ってください！';
htmlMsg[htmlMsgKey.INBOX_CONTEST_END_SOON.str] = '<b>{0}</b>はあと{1}日で終了します。頑張ってください！';
htmlMsg[htmlMsgKey.INBOX_CONTEST_INVITATION.str] = '<b>{0}</b>があなたをコンテストに招待しました<b>{1}</b>';
htmlMsg[htmlMsgKey.REFERRAL_INVALID_CODE.str] = 'Your code is invalid, please try again.';
htmlMsg[htmlMsgKey.REFERRAL_MUTUAL_INVITE.str] = 'You already invited <b>{0}</b> to join, try another one!';
htmlMsg[htmlMsgKey.REFERRAL_INVITE_SELF.str] = 'You cannot invite yourself';
htmlMsg[htmlMsgKey.REFERRAL_CONFIRMED.str] = '<b>{0}</b>より紹介コードが認証されました。あなたのアカウントに{1}コインが追加されます！';
htmlMsg[htmlMsgKey.FUEL_EXCHANGE.str] = 'Good job! Your FDT Fuel score is above <b>{0}</b>! You can now exchange <b>{1}</b> fuel points for 1 coin.';
htmlMsg[htmlMsgKey.FUEL_FULL.str] = 'Wow! Your FDT Fuel is full! Exchange for coins now!';
htmlMsg[htmlMsgKey.FUEL_LOW.str] = 'Your FDT Fuel is almost consumed. Make trades or post on “Timelines” to gain more Fuel now!';
htmlMsg[htmlMsgKey.SCHOOL_PASS.str] = 'Your student ID is verified!';
htmlMsg[htmlMsgKey.SCHOOL_REJECTED.str] = 'Your student ID is invalid or inconsistent with the format, please re-upload or contact customer service staff. (Please verify your student ID ASAP in order to appear on the ranking list when you participate in a campus contest.)';
htmlMsg[htmlMsgKey.SCHOOL_REMIND.str] = 'Your student ID will be expiring soon, please upload your new student ID as soon as possible.';
htmlMsg[htmlMsgKey.SCHOOL_EXPIRED.str] = 'Your student ID has expired, please upload a new student ID. (Please verify your student ID again ASAP in order to appear on the ranking list when you participate in a campus contest.)';

module.exports = htmlMsg;
